### ISSUE TITLE
Some updates may be needed

### ISSUE THREAD

**Issue by jkleiser** [freddyrangel/playing-with-react-and-d3#3]
When I run `npm i`, I get this:

> npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

and this:

> npm WARN babel-eslint@5.0.4 requires a peer of eslint@<2.3.0 but none was installed.

Then I do `npm run start`, and I get this:

> npm ERR! Darwin 15.4.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
> npm ERR! node v5.6.0
> npm ERR! npm  v3.6.0
> npm ERR! code ELIFECYCLE
> npm ERR! playing-with-react-and-d3@1.0.0 start: `webpack-dev-server`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the playing-with-react-and-d3@1.0.0 start script 'webpack-dev-server'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the playing-with-react-and-d3 package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     webpack-dev-server

**Comment by freddyrangel** [comment]
That's odd @jkleiser. I couldn't reproduce on my side. Would you mind telling me what version of Node and NPM you're using? You can do this via `node --version & npm --version`

**Comment by jkleiser** [comment]
As can be seen from the ERR lines I got, I was using node v5.6.0 and npm v3.6.0.
I have now installed node v5.10.1 and npm 3.8.3, and cloned your project anew. When I run `npm i` in the "unfinished", I now get this:

> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

I don't remember the warning re. jade->pug from my last try, it's probably something new.
When I now do `npm run start`, I get more or less the same errors as before, except now it's

> npm ERR! node v5.10.1
> npm ERR! npm  v3.8.3

Can it be that I have some modules installed globally that are causing problems?

**Comment by freddyrangel** [comment]
I switched over to node v5.6.0 and I'm getting similar warnings about Jade but no errors when trying `npm run start`. Have you tried removing the node_modules directory and running `npm cache clean & npm prune & npm i`? That might do the trick.

**Comment by jkleiser** [comment]
I removed the node_modules directory from 'unfinished' and ran `npm cache clean & npm prune & npm i`, but that didn't change very much. The `npm i`still ends with this:

> npm WARN babel-eslint@5.0.4 requires a peer of eslint@<2.3.0 but none was installed.

The `npm run start`still produces errors. See attached zipped log file.
[npm-debug.log.zip](https://github.com/freddyrangel/playing-with-react-and-d3/files/214798/npm-debug.log.zip)

**Comment by freddyrangel** [comment]
Interesting. In any case we don't need ESLint in this project. I decided to remove it. Hopefully that fixes the issue.

**Comment by jkleiser** [comment]
Thanks! Now it works.

**Comment by freddyrangel** [comment]
Great! Thanks for sticking with this issue. I'm sure you weren't the only one.
